name: Docker Workflow

on:
    workflow_dispatch:
        inputs:
            tag:
                description: "Tag to simulate"
                required: true
    push:
        tags:
            - "v*"

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Determine Tag Name
              id: tag_name
              run: |
                  if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
                    echo "::set-output name=tag::${{ github.event.inputs.tag }}"
                  else
                    echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"
                  fi

            - name: Determine if latest tag
              id: latest_tag
              run: |
                  current_tag=${{ steps.tag_name.outputs.tag }}
                  all_tags=$(echo "$current_tag" && git tag -l | grep -v -E 'alpha|beta')
                  latest_stable_tag=$(echo "$all_tags" | sort -V | tail -n1)
                  if [[ "$current_tag" == "$latest_stable_tag" ]]; then
                    echo "::set-output name=is_latest::true"
                  else
                    echo "::set-output name=is_latest::false"
                  fi

            - name: Extract repository name
              id: repo_name
              run: echo "::set-output name=name::$(echo ${GITHUB_REPOSITORY##*/})"

            - name: Build and push image
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: |
                      ghcr.io/${{ github.repository }}/${{ steps.repo_name.outputs.name }}:${{ steps.tag_name.outputs.tag }}
                      ${{ steps.latest_tag.outputs.is_latest == 'true' && 'ghcr.io/${{ github.repository }}/${{ steps.repo_name.outputs.name }}:latest' }}
                  platforms: linux/amd64,linux/arm64
